apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: loyalty-services
  labels:
    app: customer-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: customer-service
