apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: loyalty-services
  labels:
    app: transaction-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: grpc
  selector:
    app: transaction-service
